config/routes.rb
Rails.application.routes.draw do
  resources :users

  # Session handling routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Account actions

  resources :accounts, only: [:show]
  get 'accounts/:id/balance', to: 'accounts#balance', as: :balance
  get 'accounts/:id/transfers/new', to: 'accounts#transfer', as: :transfer
  post 'accounts/:id/transfers', to: 'accounts#create_transfer', as: :transfers

  root to: 'sessions#new'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :entries

  def credit(amount)
    entries.build entry(amount)
  end

  def debit(amount)
    entries.build entry(-amount)
  end

  def balance
    entries.reduce(0) { |total, entry| total + entry.amount }
  end

  def user_name
    user.name
  end

  private

  # Returns a hash representation of a new book
  #
  # The idea of Account class is to work as a read only model for entries
  # and the only way to add an object to a collection in Rails without
  # persisting it is to using the +collection.build+ method which takes a
  # hash with attributes as parameter.
  def entry(amount)
    Entry.book(self, amount).as_json
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_one :account

  validates_presence_of :when
  validates_presence_of :amount

  # Returns a new instance of Entry booked for an account with given amount
  # booked to now
  #
  # This method is a named constructor to make the domain clearer.
  def self.book(account, amount)
    new(
      account_id: account.id,
      when: DateTime.now,
      amount: BigDecimal.new(amount.to_s)
    )
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :debit_entry, class_name: Entry
  belongs_to :credit_entry, class_name: Entry

  class << self
    def schedule(left_account, right_account, amount)
      raise InvalidAccountError.new unless left_account && right_account
      raise IllegalOperationError.new unless amount > 0

      transaction = new
      transaction.build_debit_entry debit_entry(left_account, amount)
      transaction.build_credit_entry credit_entry(right_account, amount)

      transaction
    end

    private

    def credit_entry(account, amount)
      account.credit(amount).as_json
    end

    def debit_entry(account, amount)
      account.debit(amount).as_json
    end
  end


  def commit(memo)
    self.memo = memo
    raise InvalidTransactionError.new unless can_be_commited? && save
    self
  end

  private

  def can_be_commited?
    if debit_entry && credit_entry
      debit_entry.amount + credit_entry.amount == 0
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :account

  validates_presence_of :name
  validates_presence_of :email

  has_secure_password
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authorize

  rescue_from InvalidAccountError, with: :not_found

  def show
    @account = ChartOfAccounts.load(params[:id])
  end

  def balance
    @account = ChartOfAccounts.load(params[:id])
  end

  def transfer
    @another_accounts = load_accounts_to_transfer
    @account = ChartOfAccounts.load(params[:id])
  end

  def create_transfer
    Transfer.perform(params[:id], params[:destination_id], params[:amount])
    flash[:success] = 'Transfer completed!'
    redirect_to account_path
  rescue InvalidAccountError, IllegalOperationError, InsuficientFundsError => e
    flash[:error] = e.message
    redirect_to transfer_path
  end

  private

  def load_accounts_to_transfer
    ChartOfAccounts.other_than(params[:id]).map do |account|
      [ account.user_name, account.id ]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  def not_found
    flash[:error] = 'Account not found'
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to account_path(current_user.account) if current_user
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to account_path(user.account)
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      account = ChartOfAccounts.new_account_for user
      redirect_to account_path(account.id)
    else
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user)
          .permit(
            :name,
            :email,
            :password,
            :password_confirmation
          )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/balance.html.erb
<h1>Your Balance</h1>

<div>
  Your current balance is: R$ <%= @account.balance %>
</div>

app/views/accounts/show.html.erb
<h1>Welcome to your account, <%= @account.user_name %></h1>

<div>
    <ul>
        <li><%= link_to 'Transfer', transfer_path(@account) %>
        <li><%= link_to 'Your Balance', balance_path(@account) %>
    </ul>
</div>

app/views/accounts/transfer.html.erb
<h1>Transfer Funds</h1>

<%= form_tag transfers_path do %>

  Destination account: <%= select_tag :destination_id, options_for_select(@another_accounts), { prompt: 'Select the destination account' } %>
  Amount: <%= text_field_tag :amount %>
  <%= hidden_field_tag :source_id, @account.id %>
  <%= submit_tag "Submit" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magnetis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      Signed in as <%= current_user.name %> | <%= link_to "Logout", logout_path %>
    <% else %>
      <%= link_to 'Login', login_path %> | <%= link_to 'Signup', new_user_path %>
    <% end %>

    <% flash.each do |key, value| %>
        <div class="<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>